// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVEjft6-mMFJI_TXvVnvYrv-1LulF1p5o',
    appId: '1:596757421557:web:474967c67e3f8bd11bd4bc',
    messagingSenderId: '596757421557',
    projectId: 'campusconnect-3baf4',
    authDomain: 'campusconnect-3baf4.firebaseapp.com',
    storageBucket: 'campusconnect-3baf4.firebasestorage.app',
    measurementId: 'G-TPG9PTS29E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bUBpTDlyQ1eKdbAJzZDEU3QOGIT9MkQ',
    appId: '1:596757421557:android:053649f0d8f10d2c1bd4bc',
    messagingSenderId: '596757421557',
    projectId: 'campusconnect-3baf4',
    storageBucket: 'campusconnect-3baf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDWUJAK3u3SYd7aL7uH3qQeU5vl0pRGto',
    appId: '1:596757421557:ios:4296141b8bbb31c81bd4bc',
    messagingSenderId: '596757421557',
    projectId: 'campusconnect-3baf4',
    storageBucket: 'campusconnect-3baf4.firebasestorage.app',
    iosBundleId: 'com.example.cconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDWUJAK3u3SYd7aL7uH3qQeU5vl0pRGto',
    appId: '1:596757421557:ios:4296141b8bbb31c81bd4bc',
    messagingSenderId: '596757421557',
    projectId: 'campusconnect-3baf4',
    storageBucket: 'campusconnect-3baf4.firebasestorage.app',
    iosBundleId: 'com.example.cconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVEjft6-mMFJI_TXvVnvYrv-1LulF1p5o',
    appId: '1:596757421557:web:3752bc71db1cf82c1bd4bc',
    messagingSenderId: '596757421557',
    projectId: 'campusconnect-3baf4',
    authDomain: 'campusconnect-3baf4.firebaseapp.com',
    storageBucket: 'campusconnect-3baf4.firebasestorage.app',
    measurementId: 'G-X64DCTZDD8',
  );
}
